// Generated by CoffeeScript 1.7.1
(function() {
  var DBFParser, DBFQuery;

  DBFParser = require("./DBFParser");

  DBFQuery = (function() {
    function DBFQuery(from, where, orderby, fields, encoding, callback) {
      this.from = from;
      this.where = where;
      this.orderby = orderby;
      this.fields = fields != null ? fields : '*';
      this.encoding = encoding != null ? encoding : 'cp866';
      this.callback = callback;
      this.records = [];
      this.dbfParser = new DBFParser(this.from, this.encoding);
      this.dbfParser.on('record', (function(_this) {
        return function(record) {
          var check, fieldName, obj, _i, _j, _len, _len1, _ref, _w_;
          check = true;
          if (typeof _this.where === 'function') {
            check &= _this.where(record);
          } else if ((_this.where != null) && typeof _this.where === 'object') {
            _ref = _this.where;
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              _w_ = _ref[_i];
              check &= (function() {
                switch (_w_[1].toLowerCase()) {
                  case '=':
                    return record[_w_[0]] === _w_[2];
                  case '!=':
                    return record[_w_[0]] !== _w_[2];
                  case '<':
                    return record[_w_[0]] < _w_[2];
                  case '<=':
                    return record[_w_[0]] <= _w_[2];
                  case '>':
                    return record[_w_[0]] > _w_[2];
                  case '>=':
                    return record[_w_[0]] >= _w_[2];
                  case 'like':
                    return record[_w_[0]].toString().match(_w_[2]) !== null;
                }
              })();
            }
          }
          if (record['_deleted_'] === false && check) {
            if ((fields != null) && fields !== '*') {
              obj = {};
              for (_j = 0, _len1 = fields.length; _j < _len1; _j++) {
                fieldName = fields[_j];
                obj[fieldName] = record[fieldName];
              }
            } else {
              obj = record;
            }
            return _this.records.push(obj);
          }
        };
      })(this));
      this.dbfParser.on('end', (function(_this) {
        return function() {
          if ((_this.orderby != null) && typeof _this.orderby === 'object') {
            DBFQuery.sort(_this.records, _this.orderby);
          } else if (typeof _this.orderby === 'function') {
            _this.orderby(_this.records);
          }
          return typeof _this.callback === "function" ? _this.callback(_this.records) : void 0;
        };
      })(this));
    }

    DBFQuery.prototype.selectSimple = function() {
      this.records = [];
      return this.dbfParser.parse();
    };

    return DBFQuery;

  })();

  DBFQuery.leftJoin = function(arr1, field1, arr2, field2) {
    var cnt, rec1, rec2, _i, _j, _len, _len1;
    if ((arr1 == null) || (arr2 == null) || !field1 || (field2 == null)) {
      return -1;
    }
    cnt = 0;
    for (_i = 0, _len = arr1.length; _i < _len; _i++) {
      rec1 = arr1[_i];
      for (_j = 0, _len1 = arr2.length; _j < _len1; _j++) {
        rec2 = arr2[_j];
        if (rec1[field1] === rec2[field2]) {
          rec1[field1] = rec2;
          cnt++;
          break;
        }
      }
      if (typeof rec1[field1] !== 'object') {
        rec1[field1] = null;
      }
    }
    return cnt;
  };

  DBFQuery.sort = function(arr, fields) {
    return arr.sort(function(x1, x2) {
      var a, b, field, _i, _len;
      for (_i = 0, _len = fields.length; _i < _len; _i++) {
        field = fields[_i];
        a = x1[field].toString();
        b = x2[field].toString();
        if (a < b) {
          return -1;
        } else if (a > b) {
          return 1;
        }
      }
      return 0;
    });
  };

  module.exports = DBFQuery;

}).call(this);
